services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80"
      - "5342:5341"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
      - SEQ_API_AUTHENTICATION_ENABLED=true
      - SEQ_API_ADMIN_USERNAME=admin
      - SEQ_API_ADMIN_PASSWORD=admin
    volumes:
      - ./seq-data:/data
    restart: unless-stopped